### ISSUE TITLE
AD/O365 sync: send reminder emails to users about imminent password expiry

### ISSUE THREAD

**Issue by ropable** [parksandwildlife/oim-cms#145]

**Comment by ropable** [comment]
Email should include instructions how to reset password, plus link to self-service portal.

**Comment by tawazz** [comment]
-    is there any email templates the department currently use

**Comment by ropable** [comment]
No templates, but here is an example of the process: https://github.com/parksandwildlife/prs/blob/master/prs2/referral/views.py#L193

**Comment by adonm** [comment]
Also if you want to use consistent CSS in emails, we typically use foundation (also for web stuff) - see http://foundation.zurb.com/emails.html

**Comment by tawazz** [comment]
![email](https://cloud.githubusercontent.com/assets/12362544/19264531/a2d7ab98-8fd3-11e6-95f3-ba5427327e55.PNG)

any thoughts on my current implementation of the email.

**Comment by ropable** [comment]
👍 That's looking pretty nice. Will review and/or crib for my own purposes ;)

**Comment by adonm** [comment]
Also use this url for password reset - https://account.activedirectory.windowsazure.com/ChangePassword.aspx

Other one is an old internal app, but people should be using Office 365 for passwrord change these days

**Comment by tawazz** [comment]
alright, I will make that change

**Comment by adonm** [comment]
actually ask ash he can help you make that a shortcut like https://chpass.dpaw.wa.gov.au heh

**Comment by tawazz** [comment]
okay, I will ask him :)

**Comment by ropable** [comment]
Implemented redirect in Wagtail: https://oim.dpaw.wa.gov.au/changepassword
