### ISSUE TITLE
View to allow application custodians the ability to edit some ITSystem fields

### ISSUE THREAD

**Issue by ropable** [parksandwildlife/oim-cms#191]
Allow custodians to edit the following fields: description, notes, documentation, technical_documentation, system_reqs, workaround, recovery_docs, system_creation_date, critical_period, alt_processing, technical_recov, post_recovery, user_notification, unique_evidence, point_of_truth, legal_need_to_retain

**Comment by xzzy** [comment]
Displaying Fields Friendly: 

description
notes 
documentation
technical_documentation
system_reqs
workaround
recovery_docs
system_creation_date
critical_period
alt_processing
technical_recov
post_recovery
user_notification
unique_evidence
point_of_truth
legal_need_to_retain

**Comment by xzzy** [comment]
IT System Register Template will need to be adjusted within /admin for a edit button to be added.

**Comment by xzzy** [comment]
Have added permission check rules to Form and AIP limited to Custodian, Super User & OIM Staff user group
