### ISSUE TITLE
Functionality to manage and log AD account modifications

### ISSUE THREAD

**Issue by ropable** [parksandwildlife/oim-cms#196]
Modify DepartmentUserResource class to:
1. Have a clean division between "Create" and "Update" methods (see restless docs: http://restless.readthedocs.io/en/latest/)
2. Undertake logging for create/update actions (what changed, by whom) to new file: logs/ad_sync_actions.log

**Comment by tawazz** [comment]
The way the ad_sync script is written there is currently no way to separate the `Create` and `Update` methods

**Comment by ropable** [comment]
We'll alter the AD sync scripts to use POST for creation of a user and PUT for changes.

**Comment by tawazz** [comment]
That will be good, because its quite hard to figure out what has changed at the moment
