### ISSUE TITLE
Refactor the "create Freshdesk ticket" view to use v2 API

### ISSUE THREAD

**Issue by ropable** [parksandwildlife/oim-cms#202]
The Freshdesk v1 API is being deprecated, need to refactor this view.
http://developer.freshdesk.com/api/#create_ticket

**Comment by tawazz** [comment]
#upgrade issues

* source 4 `forum` doesn't exist anymore in fresh desk api v2
![source](https://cloud.githubusercontent.com/assets/12362544/19296959/d1e597f2-9072-11e6-8380-5960c009fac0.PNG)

* I cant find the fresh desk page in the cms so that i can test some of the changes I made

**Comment by ropable** [comment]
I'm unsure if the API endpoint is used in the CMS, but just try to test the endpoint programmatically (using requests library or similar). See some of the unit tests for examples (test-api.py).

**Comment by tawazz** [comment]
I made all the changes in api v2, I tested the endpoints using postman, but they seem to require extra parameters different to the ones in the code.
