### ISSUE TITLE
Upgrade Django to v1.10.x

### ISSUE THREAD

**Issue by ropable** [parksandwildlife/oim-cms#221]
Test the upgrade from 1.9.9 to 1.10.2(?). Check the following:
- Unit tests
- Content admin authoring (create, update, publish)
- Django admin functions (create, update, delete, reports)

Make a note of required deployment steps (migrations, etc.)

**Comment by tawazz** [comment]
- restless does not currently support django v1.10.x .  
- I have a fork of restless https://github.com/tawazz/restless with the fixes to support v1.10.x , maybe we can package the fork to **static.dpaw**.
-  I have tested with local package and it works fine

**Comment by adonm** [comment]
It may also be worth switching to django-rest-framework at some point, not urgent

**Comment by tawazz** [comment]
@ropable  what are we checking for here https://github.com/parksandwildlife/oim-cms/blob/master/oim_cms/test_api.py#L201

Im having an error `list indices must be integers, not str` when testing the django_rest_framework

**Comment by ropable** [comment]
restless v2.0.3 now support Django 1.10, so no need for a custom fork. The upgrade has also required django-rest-framework to be updated to >=3.4.0 (used by the catalogue app) - I need to test this separately.
