### ISSUE TITLE
Unable to add Hardware record

### ISSUE THREAD

**Issue by wilsonc86** [parksandwildlife/oim-cms#226]
Attempting to add a new registers.hardware record fails with an error, form also seems to be missing the Name field

**Comment by ropable** [comment]
The intention was that Hardware objects would only ever be created from PDQ Inventory scans. If they're not all coming through, we might need to change this behaviour.

**Comment by ropable** [comment]
We're going to merge the Hardware model into the tracking.Computer/Mobile model.
